spring.application.name=BookManagementSystem 


spring.datasource.url=jdbc:mysql://localhost:3306/book_management_sys?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Smit@001

spring.jpa.hibernate.ddl-auto = update


jwt.secret=secret
